### ISSUE TITLE
点击开始安装之后一直显示数据提交中

### ISSUE THREAD

**Issue by JerryYang666** [majiameng/MengPHP#1]
数据库连接测试成功，点击开始安装之后，一直显示数据提交中。

**Comment by majiameng** [comment]
一般出现这种情况就是php的有些函数禁用了,权限问题,在 "MengPHP/app/install/controller/Error.php" 文件中打断点查找一下

**Comment by majiameng** [comment]
> 数据库连接测试成功，点击开始安装之后，一直显示数据提交中。

一般出现这种情况就是php的有些函数禁用了,权限问题,在 "MengPHP/app/install/controller/Error.php" 文件中打断点查找一下
